/* Perspective flight: depth moves continuously; player steers across the view. */
const fallStyle=document.createElement('link');fallStyle.rel='stylesheet';fallStyle.href='fall.css';document.head.append(fallStyle);fallStyle.onload=resize;
const names=[['游戏项目','Game projects'],['研究项目','Research projects'],['课程与作业','Courses & assignments'],['兴趣','Interests'],['经历','Experience']];nodes.forEach((n,i)=>{n.zh=names[i][0];n.en=names[i][1];if(content[n.id]){content[n.id].zh=n.zh;content[n.id].en=n.en}});
$('.intro h1').dataset.zh='赵卓羲 · 个人主页';$('.intro h1').dataset.en='Josie Zhao · Personal website';
const pause=document.createElement('button');pause.id='flight-pause';$('.intro').append(pause);let flightPaused=false;
const oldText=renderText;renderText=()=>{oldText();document.title=tr('赵卓羲 · 个人主页','Josie Zhao · Personal website');$('.world-footer>span').textContent=tr('持续下落 · 方向键移动 · 碰到书本打开内容','Continuous descent · Steer with arrow keys · Touch a book to open');$('#reset').textContent=tr('重新开始','Restart');pause.textContent=flightPaused?tr('继续下落','Resume'):tr('暂停下落','Pause');$('#world').setAttribute('aria-label',tr('持续下落的书本场景，WASD 或方向键移动角色，碰到书本进入内容。','Continuous falling scene. Move with WASD or arrow keys and touch a book to open its content.'))};
pause.onclick=()=>{flightPaused=!flightPaused;keys.clear();renderText()};
let flightTime=0,prevTime=0,cooldown=0,steer={x:0,y:.35},pointer=null;const range=18,speed=2.3,bookColors=['#79aada','#31537c','#bccfe4','#65a9bb','#879cbf'];
const books=Array.from({length:15},(_,i)=>({id:i%5,z:2+i*1.18,x:Math.cos(i*2.4)*1.05,y:Math.sin(i*2.4)*.65+.15,angle:(i%3-1)*.22,passed:false}));
function project(x,y,z){const f=Math.min(w,h)*1.1,k=f/(z+1.1);return{x:w*.5+x*k,y:h*.43+y*k,k}}
function polygon(points,color,stroke){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=color;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=.7;ctx.stroke()}}
function cubeBook(b){const n=nodes[b.id],z=b.z,ang=b.angle+Math.sin(flightTime*.7+b.id)*.1,c=Math.cos(ang),s=Math.sin(ang);const p=(x,y,d=0)=>project(b.x+x*c-y*s,b.y+x*s+y*c,z+d);const corners=[p(-.28,-.36),p(.28,-.36),p(.28,.36),p(-.28,.36)],back=[p(-.28,-.36,.09),p(.28,-.36,.09),p(.28,.36,.09),p(-.28,.36,.09)];polygon([corners[1],back[1],back[2],corners[2]],'#e6edf6','#afbdd0');polygon([corners[2],back[2],back[3],corners[3]],'#f9fbfd','#afbdd0');polygon(corners,bookColors[b.id],'#57769c');polygon([p(-.25,-.34),p(-.20,-.34),p(-.20,.34),p(-.25,.34)],'#ffffff35');const center=project(b.x,b.y,z);if(z<10){ctx.save();ctx.translate(center.x,center.y);ctx.rotate(ang);ctx.fillStyle=b.id===2?'#365577':'#f5f9ff';ctx.textAlign='center';ctx.textBaseline='middle';const fs=Math.max(10,Math.min(19,center.k*.075));ctx.font=`${fs}px Arial`;const text=n[lang];if(lang==='en'){text.split(' ').forEach((word,i,a)=>ctx.fillText(word,0,(i-(a.length-1)/2)*fs*1.3,center.k*.47))}else ctx.fillText(text,0,0,center.k*.47);ctx.font=`${Math.max(9,fs*.6)}px Georgia`;ctx.fillText('0'+(b.id+1),0,center.k*.23);ctx.restore()}}
function playerScreen(){return{x:w*.5+steer.x*w*.32,y:h*.66+steer.y*h*.2}}
canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect();pointer={x:Math.max(-1,Math.min(1,((e.clientX-r.left)/w-.5)/.32)),y:Math.max(-1,Math.min(1,((e.clientY-r.top)/h-.66)/.2))};target=null;canvas.focus({preventScroll:true})});
window.addEventListener('keydown',()=>pointer=null,true);
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key))pointer=null;});
$('#reader').addEventListener('close',()=>{cooldown=2;books.forEach(b=>{if(b.z<1.5){b.z+=range;b.passed=false}});pointer=null});
$('#reset').onclick=()=>{visited.clear();books.forEach((b,i)=>{b.z=2+i*1.18;b.passed=false});steer={x:0,y:.35};cooldown=1;pointer=null;renderText()};
function frame(t){const dt=prevTime?Math.min((t-prevTime)/1000,.04):0;prevTime=t;const run=!flightPaused&&!$('#reader').open&&!document.hidden;if(run){flightTime+=dt;cooldown=Math.max(0,cooldown-dt);let dx=(keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has('a')?1:0),dy=(keys.has('ArrowDown')||keys.has('s')?1:0)-(keys.has('ArrowUp')||keys.has('w')?1:0);if(pointer){dx=pointer.x-steer.x;dy=pointer.y-steer.y;if(Math.hypot(dx,dy)<.03)pointer=null;else{const l=Math.hypot(dx,dy);dx/=l;dy/=l}}steer.x=Math.max(-1,Math.min(1,steer.x+dx*dt*1.1));steer.y=Math.max(-1,Math.min(1,steer.y+dy*dt*1.1));books.forEach(b=>{b.z-=speed*dt;if(b.z<-.65){b.z+=range;b.passed=false}})}
ctx.clearRect(0,0,w,h);const bg=ctx.createRadialGradient(w*.5,h*.43,0,w*.5,h*.43,Math.max(w,h)*.8);bg.addColorStop(0,'#f9fcff');bg.addColorStop(.25,'#e4effa');bg.addColorStop(.65,'#bfd5ea');bg.addColorStop(1,'#8fabc9');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);
// Tunnel bands repeatedly approach the camera, giving a continuous depth cue.
for(let j=28;j>=0;j--){const z=(j*.72-flightTime*speed% .72);if(z<.05)continue;const pts=[];for(let i=0;i<8;i++){const a=i*Math.PI/4;pts.push(project(Math.cos(a)*2.25,Math.sin(a)*1.65,z))}ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.strokeStyle=j%4===0?'#6f93bc55':'#8baac533';ctx.lineWidth=j%4===0?2:1;ctx.stroke()}
for(let i=0;i<8;i++){const a=i*Math.PI/4,far=project(Math.cos(a)*2.25,Math.sin(a)*1.65,21),close=project(Math.cos(a)*2.25,Math.sin(a)*1.65,.05);ctx.beginPath();ctx.moveTo(far.x,far.y);ctx.lineTo(close.x,close.y);ctx.strokeStyle='#829ab54d';ctx.lineWidth=2;ctx.stroke()}
for(let i=0;i<45;i++){const z=(i*.41-flightTime*speed*.7% .41)+.15,a=i*2.399,p=project(Math.cos(a)*1.8,Math.sin(a)*1.2,z),q=project(Math.cos(a)*1.8,Math.sin(a)*1.2,z+.13);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.strokeStyle='#f8fcffa8';ctx.lineWidth=1.5;ctx.stroke()}
const ps=playerScreen();books.slice().sort((a,b)=>b.z-a.z).forEach(b=>{if(b.z>-.5)cubeBook(b);if(run&&cooldown===0&&!b.passed&&b.z<.62&&b.z>.05){const p=project(b.x,b.y,b.z);if(Math.abs(p.x-ps.x)<p.k*.29+20&&Math.abs(p.y-ps.y)<p.k*.36+20){b.passed=true;cooldown=2;keys.clear();pointer=null;openReader(nodes[b.id].id)}}});
const size=Math.max(65,Math.min(112,w*.085));ctx.save();ctx.globalAlpha=.35;for(let i=1;i<5;i++){ctx.beginPath();ctx.ellipse(ps.x,ps.y-size*.25-i*17,size*.29/(i*.2+1),size*.11,0,0,7);ctx.strokeStyle='#ffffff';ctx.lineWidth=2;ctx.stroke()}ctx.globalAlpha=1;const wobble=run?Math.sin(flightTime*7)*.025:0;if(ditto.complete&&ditto.naturalWidth)ctx.drawImage(ditto,ps.x-size*(1+wobble)/2,ps.y-size*.75,size*(1+wobble),size*(1-wobble));ctx.restore();hint.textContent=flightPaused?tr('已暂停，可通过目录查看内容。','Paused. You can also browse the Index.'):tr('移动百变怪，碰到书本进入对应栏目。','Steer Ditto into a book to open its section.');requestAnimationFrame(frame)}
const flightReader=fillReader;fillReader=id=>{flightReader(id);const title=$('#reader-content h2');if(title)title.textContent=id==='about'?tr('关于赵卓羲','About Josie Zhao'):id==='archive'?tr('内容目录','Contents'):nodes.find(n=>n.id===id)?.[lang]||title.textContent;const lead=$('#reader-content .lead');if(lead&&id==='archive')lead.textContent=tr('选择栏目查看内容。','Select a section to view its content.');};
const renderFlight=frame;frame=t=>{if(keys.size)pointer=null;renderFlight(t)};
if(reduced)flightPaused=true;renderText();resize();$('.map-wrap').classList.add('ready');requestAnimationFrame(frame);
