import {W,H,FLOOR,stairs,portals,challenges,FAILURE_END,FAILURE_PIT,FAILURE_PIT_END,createGame,stepGame,returnHome,resumeContent,enterFailure,configureCave,caveTerrain,caveRocks} from './platform-engine.mjs?v=10';
import {failures as defaults} from './failures.mjs?v=10';
import {siteConfig} from './site-config.js?v=10';
import {watchAsset,assetNotice,bindGameButton,fallbackSheet} from './asset-loader.mjs?v=10';
configureCave(siteConfig?.cave);
draw=()=>{};
// Styles are preloaded in index.html to prevent an unstyled initial frame.
content.experience={zh:'沿途经历',en:'Along the way',intro:['在不同的地方，与人一起学习和做事。','Learning and making things with people, in different places.'],items:[entry('哥伦比亚大学 · 课程助教','Columbia University · Course assistant','参与 Scheduling 课程的教学支持，在运筹学的学习之外体验知识的交流。','Supporting the Scheduling course, exploring the exchange of knowledge alongside studies in operations research.','TEACHING · 2026'),entry('百度 · 数据标注','Baidu · Data annotation','在百度参与数据标注工作。','Worked on data annotation at Baidu.','INTERNSHIP · 2024–2025'),entry('券商实习','Securities firm internship','有过券商实习经历。','I interned at a securities firm.','INTERNSHIP · 2024'),entry('武汉大学 · 校园与志愿活动','Wuhan University · Campus & volunteering','在学生组织和志愿活动中参与组织协作，把想法变成一起完成的事情。','Organizing and collaborating through student activities and volunteering, turning ideas into shared efforts.','COMMUNITY')]};
content.life.items=[...content.experience.items,...content.life.items];content.life.intro=['教育、工作、校园活动与个人兴趣。','Education, work, campus activities and personal interests.'];
nodes.splice(0,nodes.length,{id:'hi',sub:'HELLO'},{id:'make',sub:'PROJECTS'},{id:'play',sub:'GAMES'},{id:'watch',sub:'COLLECTION'});const names=[['认识了吗','Me Meeting'],['实践了吗','Me Practising'],['创造了吗','Me Creating'],['快乐了吗','Me Enjoying']];
nodes.forEach((n,i)=>{n.zh=names[i][0];n.en=names[i][1];if(content[n.id])Object.assign(content[n.id],{zh:n.zh,en:n.en})});
$('.intro h1').dataset.zh='赵卓羲 · 个人主页';$('.intro h1').dataset.en='Josie Zhao · Personal Website';
let game=createGame(),stories=siteConfig?.cave?.rocks||defaults,loaded=true,lastFrame=0,accumulator=0;
const held=new Set(),pulses={jump:false,action:false,transform:false};const sheets={ditto:fallbackSheet('ditto'),props:fallbackSheet('props'),riolu:fallbackSheet('riolu')};
const surface=document.createElement('canvas');surface.width=W;surface.height=H;const g=surface.getContext('2d');g.imageSmoothingEnabled=false;
const back=document.createElement('button');back.id='pixel-back';back.hidden=true;$('.intro').append(back);
const pause=document.createElement('button');pause.id='pixel-pause';$('.intro').append(pause);
const cloud=document.createElement('div');cloud.id='pixel-cloud';cloud.hidden=true;cloud.setAttribute('role','dialog');cloud.setAttribute('aria-modal','false');cloud.setAttribute('aria-label','Treasure / 宝箱');cloud.innerHTML='<small></small><p></p><button></button>';$('.map-wrap').append(cloud);
const controls=document.createElement('div');controls.className='pixel-controls';controls.innerHTML='<div><button data-key="left" aria-label="Move left / 向左">←</button><button data-key="right" aria-label="Move right / 向右">→</button></div><div><button data-key="transform">Z</button><button data-key="jump">↑</button><button data-key="action">Space</button></div>';$('.map-wrap').append(controls);
function clearInput(){held.clear();pulses.jump=pulses.action=pulses.transform=false;}
function closeCloud(){game.cloud=null;cloud.hidden=true;clearInput();canvas.focus({preventScroll:true});}
cloud.querySelector('button').onclick=closeCloud;
function home(){returnHome(game);cloud.hidden=true;clearInput();renderText();}
back.onclick=home;
pause.onclick=()=>{game.paused=!game.paused;clearInput();renderText();};
$('#reset').onclick=()=>{game=createGame();visited.clear();cloud.hidden=true;clearInput();renderText();};
const priorRender=renderText;
renderText=()=>{priorRender();document.title=tr('赵卓羲 · 个人主页','Josie Zhao · Personal Website');$('.intro h1').textContent=game.scene==='failure'?tr('小心！','Watch out!'):tr('赵卓羲 · 个人主页','Josie Zhao · Personal Website');back.hidden=game.scene!=='failure';back.textContent=tr('返回主页','Back home');pause.textContent=game.paused?tr('继续 · P','Resume · P'):tr('暂停 · P','Pause · P');pause.setAttribute('aria-pressed',String(game.paused));$('#reset').textContent=tr('重新开始','Restart');$('.world-footer>span').textContent=game.scene==='failure'?tr('← → / A D 移动 · Z 变身 · Space 碎岩 · W / ↑ 跳跃','← → / A D move · Z transform · Space smash · W / ↑ jump'):tr('← → / A D 移动 · W / ↑ / Space 跳跃','← → / A D move · W / ↑ / Space jump');$('#progress').textContent=visited.size+' / 4 '+tr('已浏览','viewed');controls.querySelector('[data-key="transform"]').hidden=game.scene!=='failure';canvas.setAttribute('aria-label',tr('像素平台游戏：左右键或 AD 移动，W、上键或空格跳跃。也可以通过目录直接浏览内容。','Pixel platform game: arrows or AD to move; W, up or Space to jump. Contents also provides direct access.'));if(game.cloud!==null)showCloud();};
const priorReader=fillReader;
fillReader=id=>{priorReader(id);const title=$('#reader-content h2');if(title)title.textContent=id==='about'?tr('关于赵卓羲','About Josie Zhao'):id==='archive'?tr('内容目录','Contents'):nodes.find(n=>n.id===id)?.[lang]||title.textContent;
 if(nodes.some(n=>n.id===id)&&sheets.ditto){const c=document.createElement('canvas');c.width=84;c.height=84;c.className='reader-pixel';c.setAttribute('role','img');c.setAttribute('aria-label','Ditto / 百变怪');const p=c.getContext('2d');p.imageSmoothingEnabled=false;const f=sheets.ditto[0];p.drawImage(f,0,0,f.width,f.height,8,8,68,68);$('#reader-content').prepend(c);}
 if(id==='about'){const credit=document.createElement('p');credit.className='sprite-credit';credit.append(document.createTextNode('Riolu sprites: CHUNSOFT · '));const link=document.createElement('a');link.href='https://github.com/PMDCollab/SpriteCollab/tree/master/sprite/0447';link.target='_blank';link.rel='noopener noreferrer';link.textContent='PMDCollab / SpriteCollab';credit.append(link);$('#reader-content').append(credit);}const lead=$('#reader-content .lead');if(lead&&id==='archive')lead.textContent=tr('选择栏目查看内容。','Choose a section.');
};
$('#reader').addEventListener('close',()=>{resumeContent(game);clearInput();canvas.focus({preventScroll:true});});
window.addEventListener('blur',clearInput);document.addEventListener('visibilitychange',()=>{clearInput();lastFrame=0;accumulator=0;});
function press(k){if(k==='left'||k==='right'||k==='run')held.add(k);else if(k==='transform')pulses.transform=true;else if(k==='jump')pulses.jump=true;else if(k==='action'){if(game.cloud!==null){closeCloud();return}if(game.scene==='failure'&&game.form==='riolu')pulses.action=true;else pulses.jump=true;}}
window.addEventListener('keydown',e=>{if($('#reader').open||e.metaKey||e.ctrlKey||e.altKey)return;const k=e.key.toLowerCase();const map={arrowleft:'left',a:'left',arrowright:'right',d:'right',arrowup:'jump',w:'jump',' ':'action',z:'transform',shift:'run'};if(map[k]){e.preventDefault();e.stopImmediatePropagation();if(!e.repeat)press(map[k]);}else if(k==='p'){e.preventDefault();if(!e.repeat)pause.click();}else if(k==='escape'&&game.scene==='failure'){e.preventDefault();home();}else if(k==='enter'&&game.cloud!==null){e.preventDefault();closeCloud();}},true);
window.addEventListener('keyup',e=>{const k=e.key.toLowerCase();if(['arrowleft','a'].includes(k))held.delete('left');if(['arrowright','d'].includes(k))held.delete('right');if(k==='shift')held.delete('run');},true);
controls.querySelectorAll('button').forEach(b=>bindGameButton(b,()=>{press(b.dataset.key);try{canvas.focus({preventScroll:true});}catch{}},()=>held.delete(b.dataset.key)));
function showCloud(){const story=stories[game.cloud]||defaults[game.cloud];cloud.hidden=false;cloud.querySelector('small').textContent=tr(...story.title);cloud.querySelector('p').textContent=tr(...story.response);cloud.querySelector('button').textContent=tr('继续 · Enter','Continue · Enter');}
async function loadStories(){if(siteConfig?.cave)return;try{const r=await fetch('failure-content.json',{cache:'no-store'});if(r.ok){const x=await r.json();if(Array.isArray(x)&&x.length===challenges.length&&x.every(s=>s.title?.length===2&&s.response?.length===2))stories=x;}}catch{}}
loadStories();window.addEventListener('focus',loadStories);
function splitSheet(im,cols=2,rows=2){return Array.from({length:cols*rows},(_,i)=>{const sw=Math.floor(im.width/cols),sh=Math.floor(im.height/rows),c=document.createElement('canvas');c.width=sw;c.height=sh;let q=c.getContext('2d');q.drawImage(im,(i%cols)*sw,Math.floor(i/cols)*sh,sw,sh,0,0,sw,sh);const data=q.getImageData(0,0,sw,sh).data;let minX=sw,minY=sh,maxX=0,maxY=0;for(let y=0;y<sh;y++)for(let x=0;x<sw;x++)if(data[(y*sw+x)*4+3]>100){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);}const cut=document.createElement('canvas');cut.width=Math.max(1,maxX-minX+1);cut.height=Math.max(1,maxY-minY+1);cut.getContext('2d').drawImage(c,minX,minY,cut.width,cut.height,0,0,cut.width,cut.height);return cut;});}
function nativeFrames(im,fw,fh,count){return Array.from({length:count},(_,i)=>{const c=document.createElement('canvas');c.width=fw;c.height=fh;const q=c.getContext('2d');q.drawImage(im,i*fw,6*fh,fw,fh,0,0,fw,fh);const d=q.getImageData(0,0,fw,fh).data;let x0=fw,y0=fh,x1=0,y1=0;for(let y=0;y<fh;y++)for(let x=0;x<fw;x++)if(d[(y*fw+x)*4+3]>100){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);}const cut=document.createElement('canvas');cut.width=x1-x0+1;cut.height=y1-y0+1;cut.getContext('2d').drawImage(c,x0,y0,cut.width,cut.height,0,0,cut.width,cut.height);return cut;});}
watchAsset('home-ditto','assets/pixel-ditto.webp',im=>{sheets.ditto=splitSheet(im);});
watchAsset('home-props','assets/pixel-props.webp',im=>{sheets.props=splitSheet(im);});
let caveAssetsStarted=false;
function loadCaveAssets(){
 if(caveAssetsStarted)return;caveAssetsStarted=true;
 watchAsset('riolu-walk','assets/riolu-walk.png',im=>{const frames=nativeFrames(im,24,40,4);sheets.riolu.splice(0,4,...frames);});
 watchAsset('riolu-attack','assets/riolu-attack.png',im=>{const frames=nativeFrames(im,72,72,15);sheets.riolu.splice(4,15,...frames);});
}
assetNotice($('.map-wrap'));
function rect(x,y,w,h,c){g.fillStyle=c;g.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h));}
function text(t,x,y,size=16,color='#66517f',align='left'){g.fillStyle=color;g.font='bold '+size+'px "Courier New", "PingFang SC", monospace';g.textAlign=align;g.fillText(t,Math.round(x),Math.round(y));}
function sprite(key,frame,x,bottom,width,flip=false){const im=sheets[key]?.[frame];if(!im)return;const height=key==='riolu'?im.height*4:width*im.height/im.width;if(key==='riolu')width=im.width*4;g.save();g.translate(Math.round(x),Math.round(bottom));if(flip)g.scale(-1,1);g.drawImage(im,0,0,im.width,im.height,-width/2,-height,width,height);g.restore();}
function terrain(x,y,width,deep=false){const cave=game.scene==='failure';rect(x,y,width,deep?H-y:24,cave?'#605080':'#77689f');rect(x+4,y,width-8,4,'#f8e7ff');rect(x,y+4,width,5,'#d6bfe9');rect(x+3,y+9,width-6,5,'#a590c7');for(let n=x+4;n<x+width-8;n+=17){const v=Math.floor(n*7)%11;rect(n,y+8+v%4,8,5,v%2?'#bdabde':'#947eba');if(!deep)rect(n+5,y+19,9,5,'#665387');}if(deep)for(let r=y+20;r<H;r+=17)for(let c=x+5;c<x+width-10;c+=22){const k=(Math.floor(c)+r)%5;rect(c+(r%34?4:0),r,k+4,k+4,k%2?'#a18ac05a':'#66528955');}for(let n=x+18;n<x+width-30;n+=97){rect(n,y-9,3,9,'#a499c7');rect(n-4,y-6,3,4,'#b7a9d6');rect(n+5,y-12,3,8,'#a499c7');if((n+x)%3===0){rect(n+18,y-10,2,10,'#b3aecf');rect(n+15,y-13,8,4,'#fbe7ff');rect(n+17,y-15,4,8,'#fbe7ff');rect(n+18,y-12,2,2,'#ddd3a0');}}}
function background(){rect(0,0,W,H,game.scene==='failure'?'#9c8ac7':'#d8caed');if(meadow.complete&&meadow.naturalWidth){g.globalAlpha=game.scene==='failure'?.15:.55;g.drawImage(meadow,0,0,W,H);g.globalAlpha=1;}for(let i=0;i<24;i++){const x=(i*173+37)%W,y=(i*71+35)%(FLOOR-90);rect(x,y,3,3,'#fffaff99');if(i%4===0){rect(x-3,y+1,9,1,'#fffaff99');rect(x+1,y-3,1,9,'#fffaff99');}}if(game.scene==='failure'){for(let layer=0;layer<3;layer++){for(let i=0;i<17;i++){const x=i*72-(game.camera*(.04+layer*.035)%72),drop=30+(i*47+layer*71)%125;rect(x,0,48,drop,['#75639855','#69568c77','#58457588'][layer]);rect(x+12,drop,24,22,['#75639855','#69568c77','#58457588'][layer]);}}}
 if(game.scene==='home'){
 }document.body.dataset.scene=game.scene;
}
function drawHome(){terrain(0,FLOOR,278,true);terrain(382,FLOOR,W-382,true);stairs.forEach(p=>terrain(p.x,p.y,p.w));text(tr('W / ↑ / Space 跳跃','W / ↑ / Space to jump'),330,FLOOR+52,14,'#715c8d','center');
 portals.forEach((p,i)=>{const o=game.opening?.section===i?game.opening.t:0;const im=sheets.props?.[0],size=34;g.save();g.translate(p.x,p.y);if(im){if(o){const spread=Math.min(o/.35,1)*12;g.drawImage(im,0,0,im.width,im.height/2,-17,-17-spread,34,17);g.drawImage(im,0,im.height/2,im.width,im.height/2,-17,spread*.4,34,17);}else g.drawImage(im,-17,-17,34,34);}g.restore();});
 if(!game.started){text(tr('← → / A D 开始移动','← → / A D to begin'),125,FLOOR-62,15,'#6e578d','center');}
}
function drawFailure(){g.save();g.translate(-Math.round(game.camera),0);caveTerrain.forEach(p=>terrain(p.x,p.y,p.w,!p.platform));for(const d of siteConfig?.cave?.decorations||[]){rect(d.x,d.y-12,2,12,'#7a9d95');if(d.kind==='flower'){rect(d.x-4,d.y-16,10,5,'#fff1ff');rect(d.x-1,d.y-18,4,9,'#f7d4ed');}else{rect(d.x-5,d.y-8,3,8,'#a4c3b3');rect(d.x+5,d.y-14,3,14,'#a4c3b3');}}
 challenges.forEach((x,i)=>{const y=caveRocks[i].y,destroyed=game.broken.includes(i);if(!destroyed){sprite('props',1,x,y,270);text(tr(...stories[i].title),x,y-205,16,'#5d497a','center');}else {sprite('props',game.attack?.index===i&&game.attack.t<.45?2:3,x,y,55);if(game.attack?.index===i){const t=game.attack.t-.24;for(let k=0;k<8;k++)rect(x+(k-3.5)*t*130,y-35-t*160+t*t*230,6,6,k%2?'#eee7ff':'#a491c3');}}});
 if(FAILURE_PIT<FAILURE_END)text(tr('掉下去，返回主页','Drop to return home'),(FAILURE_PIT+FAILURE_PIT_END)/2,FLOOR+52,15,'#66517f','center');
 if(game.x>FAILURE_PIT_END)text(tr('已到终点 · 点击「返回主页」','End of path · select Back home'),FAILURE_END-200,380,16,'#66517f');
 const next=challenges.find((x,i)=>!game.broken.includes(i)&&x>game.x-50);if(next&&next-game.x<260)text(game.form==='ditto'?tr('按 Z 变身！','Press Z to transform!'):tr('靠近后按 Space 碎岩','Move closer, then press Space'),game.x,FLOOR-100,15,'#73588f','center');g.restore();}
function drawCharacter(){let x=game.x-game.camera,y=game.y,width=game.form==='riolu'?64:42,frame=0;const walk=!game.started||Math.abs(game.vx)>0;if(game.form==='riolu'){frame=game.attack?4+Math.min(14,Math.floor(game.attack.t/.7*15)):walk?Math.floor(game.time*10)%4:0;}else frame=!game.grounded?3:walk?(Math.floor(game.time*7)%2?1:2):0;
 if(game.opening){const p=portals[game.opening.section],t=Math.max(0,Math.min(1,(game.opening.t-.2)/.65));x+=(p.x-x)*t;y+=(p.y+10-y)*t;width*=1-t*.97;g.globalAlpha=1-t;}
 // Riolu's selected native row faces left; Ditto's frames face right.
 sprite(game.form,frame,x,y,width,game.form==='riolu'?game.face>0:game.face<0);g.globalAlpha=1;
}
function render(){g.imageSmoothingEnabled=false;background();if(game.scene==='failure')loadCaveAssets();game.scene==='home'?drawHome():drawFailure();drawCharacter();if(game.paused){rect(0,0,W,H,'#e9e0f6aa');text(tr('已暂停 · P 继续','PAUSED · P TO RESUME'),W/2,H/2,24,'#66517f','center');}
 const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(r.width*dpr)||canvas.height!==Math.round(r.height*dpr)){canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);}
 ctx.setTransform(1,0,0,1,0,0);ctx.imageSmoothingEnabled=false;ctx.fillStyle='#d8caed';ctx.fillRect(0,0,canvas.width,canvas.height);const scale=Math.min(canvas.width/W,canvas.height/H),dx=(canvas.width-W*scale)/2,dy=(canvas.height-H*scale)/2;ctx.drawImage(surface,dx,dy,W*scale,H*scale);
}
function animate(t){const dt=lastFrame?Math.min((t-lastFrame)/1000,.08):0;lastFrame=t;accumulator+=dt;while(accumulator>=1/120){const e=stepGame(game,{left:held.has('left'),right:held.has('right'),run:held.has('run'),...pulses,modal:$('#reader').open||!loaded,hidden:document.hidden},1/120);pulses.jump=pulses.action=pulses.transform=false;accumulator-=1/120;if(e?.type==='page'){openReader(nodes[e.section].id);clearInput();}if(e?.type==='failure'||e?.type==='home'){clearInput();renderText();}if(e?.type==='cloud'){showCloud();clearInput();cloud.querySelector('button').focus();}}
 render();requestAnimationFrame(animate);}
let meadow=new Image();watchAsset('home-background','assets/pixel-meadow.webp',im=>{meadow=im;});
await import('./refinement.js?v=16');
renderText();const previewRoute=new URLSearchParams(location.search).get('preview');if(previewRoute==='cave'){enterFailure(game);renderText();}else if(nodes.some(n=>n.id===previewRoute))openReader(previewRoute);requestAnimationFrame(animate);
