/* A fixed-camera, illustrated game scene. All movement and collisions are live. */
draw=()=>{};
const roomStyle=document.createElement('link');roomStyle.rel='stylesheet';roomStyle.href='room.css';document.head.append(roomStyle);roomStyle.onload=resize;
const scene=new Image(),ditto=new Image();scene.src='assets/bookroom.png';ditto.src='assets/ditto.png';
const roomPositions=[[.31,.41],[.49,.29],[.71,.40],[.70,.61],[.38,.63]];
nodes[4].id='experience';nodes[4].zh='沿途经历';nodes[4].en='Along the way';nodes[4].sub='PEOPLE & PLACES';
content.experience={zh:'沿途经历',en:'Along the way',intro:['在不同的地方，与人一起学习和做事。','Learning and making things with people, in different places.'],items:[entry('哥伦比亚大学 · 课程助教','Columbia University · Course assistant','参与 Scheduling 课程的教学支持，在运筹学的学习之外体验知识的交流。','Supporting the Scheduling course, exploring the exchange of knowledge alongside studies in operations research.','TEACHING · 2026'),entry('百度 · 数据与知识平台','Baidu · Data & knowledge platform','参与语言模型训练数据的预处理，围绕 LaTeX 文档开展结构化提取与校验工作。','Worked on preprocessing language-model training data, including structured extraction and validation of LaTeX documents.','INTERNSHIP · 2024–2025'),entry('西部证券 · 策略与量化研究','Western Securities · Strategy & quantitative research','参与数据采集、清洗和研究支持，用统计与计算方法理解实际问题。','Contributed to data collection, cleaning and research support, using statistics and computation to explore practical questions.','INTERNSHIP · 2024'),entry('武汉大学 · 校园与志愿活动','Wuhan University · Campus & volunteering','在学生组织和志愿活动中参与组织协作，把想法变成一起完成的事情。','Organizing and collaborating through student activities and volunteering, turning ideas into shared efforts.','COMMUNITY')]};
nodes.forEach((n,i)=>{[n.x,n.y]=roomPositions[i];n.r=24});
player={x:.53,y:.67};target=null;let moving=false,roomLast=0,arrivalLock=null,bumpAt=-1000,sceneReady=false;
const baseRenderText=renderText;
renderText=function(){baseRenderText();document.title=tr('赵卓羲 — 蓝色书房','Josie Zhao — The blue reading room');$('#begin').textContent=tr('陪我走走 ↗','Come wander ↗');$('#world').setAttribute('aria-label',tr('浅蓝百变怪的书房。使用方向键或 WASD 移动，碰到书本打开内容。','Ditto’s blue reading room. Move with arrow keys or WASD; touch a book to explore.'));$('.world-footer>span').textContent=tr('WASD / 方向键移动 · 碰书进入 · 也可点击书本','WASD / arrow keys to move · Touch a book · Or click a book');$('.map-note').textContent=tr('五本书，五种好奇。','Five books. Five curiosities.');if($('#room-hint'))$('#room-hint').textContent=tr('点地面移动，或用 WASD / 方向键。','Click the floor, or use WASD / arrow keys.');};
$('.intro .eyebrow').dataset.zh='JOSIE’S READING ROOM / 私人书房';$('.intro .eyebrow').dataset.en='JOSIE’S READING ROOM';
$('.intro h1').dataset.zh='在蓝色里，<br>慢慢探索。';$('.intro h1').dataset.en='A little room.<br>A world within.';
$('.intro-copy').dataset.zh='我是卓羲。<br>这里收藏着我的学习、创造与喜欢。';$('.intro-copy').dataset.en='I’m Josie.<br>A collection of things I learn, make and love.';
$('.map-coordinate').innerHTML='ROOM 001<br><span>WALK · READ · WONDER</span>';
const hint=document.createElement('div');hint.id='room-hint';hint.setAttribute('role','status');$('.map-wrap').append(hint);
scene.onerror=()=>{hint.textContent=tr('场景加载失败，请刷新。也可以通过目录浏览。','The scene could not load. Refresh, or browse the Index.');};
document.addEventListener('click',e=>{const b=e.target.closest('[data-node]');if(!b)return;e.stopImmediatePropagation();const n=nodes.find(n=>n.id===b.dataset.node);arrivalLock=null;target={x:n.x,y:n.y,id:n.id};canvas.focus({preventScroll:true});},true);
const pad=document.createElement('div');pad.className='room-pad';pad.setAttribute('aria-label','Movement / 移动');pad.innerHTML='<button data-key="ArrowUp" aria-label="Up / 上">↑</button><button data-key="ArrowLeft" aria-label="Left / 左">←</button><button data-key="ArrowDown" aria-label="Down / 下">↓</button><button data-key="ArrowRight" aria-label="Right / 右">→</button>';$('.map-wrap').append(pad);
pad.querySelectorAll('button').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);target=null});['pointerup','pointercancel','lostpointercapture'].forEach(type=>b.addEventListener(type,()=>keys.delete(b.dataset.key)))});
window.addEventListener('keydown',e=>{if($('#reader').open||e.altKey||e.ctrlKey||e.metaKey)return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(k)){if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;e.preventDefault();e.stopImmediatePropagation();keys.add(k);target=null;}},true);
window.addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key),true);
document.addEventListener('visibilitychange',()=>{keys.clear();roomLast=0});
$('#reader').addEventListener('close',()=>{const n=nodes.find(n=>n.id===arrivalLock);if(n){const dx=player.x-n.x,dy=player.y-n.y,d=Math.hypot(dx,dy)||1;player.x=n.x+(d===1?0:dx/d)*.065;player.y=n.y+(d===1?.075:dy/d*.065)}target=null;keys.clear();canvas.focus({preventScroll:true});});
$('#reset').onclick=()=>{visited.clear();player={x:.53,y:.67};target=null;arrivalLock=null;renderText()};
$('#begin').onclick=()=>{canvas.focus({preventScroll:true});canvas.scrollIntoView({behavior:reduced?'auto':'smooth',block:'center'});target={x:nodes[0].x,y:nodes[0].y,id:nodes[0].id}};
const floor=[[.49,.245],[.86,.46],[.52,.86],[.14,.47]];
const bound=p=>{let inside=false;for(let i=0,j=floor.length-1;i<floor.length;j=i++){const a=floor[i],b=floor[j];if((a[1]>p.y)!==(b[1]>p.y)&&p.x<(b[0]-a[0])*(p.y-a[1])/(b[1]-a[1])+a[0])inside=!inside}if(inside)return p;let best={x:.53,y:.67},distance=Infinity;for(let i=0;i<floor.length;i++){const a=floor[i],b=floor[(i+1)%floor.length],dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((p.x-a[0])*dx+(p.y-a[1])*dy)/(dx*dx+dy*dy))),q={x:a[0]+t*dx,y:a[1]+t*dy},d=Math.hypot(q.x-p.x,q.y-p.y);if(d<distance){distance=d;best=q}}return best};
function roomLoop(now){const dt=roomLast?Math.min((now-roomLast)/1000,.04):0;roomLast=now;const s=w/1536;ctx.clearRect(0,0,w,h);if(scene.complete&&scene.naturalWidth){ctx.drawImage(scene,0,0,w,h);if(!sceneReady){sceneReady=true;$('.map-wrap').classList.add('ready')}}
 let dx=0,dy=0;moving=false;if(!$('#reader').open){dx=(keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has('a')?1:0);dy=(keys.has('ArrowDown')||keys.has('s')?1:0)-(keys.has('ArrowUp')||keys.has('w')?1:0);if(target){const b=bound(target);dx=(b.x-player.x)*w;dy=(b.y-player.y)*h;if(Math.hypot(dx,dy)<4){target=null;dx=dy=0}}const d=Math.hypot(dx,dy);if(d){moving=true;const speed=Math.max(110,w*.20);player=bound({x:player.x+dx/d*speed*dt/w,y:player.y+dy/d*speed*dt/h});}}
 let closest=null,distance=Infinity;nodes.forEach(n=>{const d=Math.hypot((n.x-player.x)*1536,(n.y-player.y)*1024);if(d<distance){closest=n;distance=d}});if(arrivalLock&&nodes.some(n=>n.id===arrivalLock&&Math.hypot((n.x-player.x)*1536,(n.y-player.y)*1024)>90))arrivalLock=null;
 near=distance<135?closest:null;document.querySelectorAll('.destination').forEach(b=>b.classList.toggle('near',b.dataset.node===near?.id));
 if(near){const x=near.x*w,y=near.y*h;ctx.save();ctx.beginPath();ctx.ellipse(x,y+22*s,65*s,24*s,0,0,Math.PI*2);ctx.fillStyle='#bddcfe55';ctx.fill();ctx.strokeStyle='#709fc5';ctx.lineWidth=1;ctx.stroke();ctx.restore();}
 if(!$('#reader').open&&distance<42&&arrivalLock!==closest?.id){arrivalLock=closest.id;bumpAt=now;target=null;keys.clear();setTimeout(()=>openReader(closest.id),180)}
 const px=player.x*w,py=player.y*h,unit=Math.max(48,92*s);let squash=1;if(now-bumpAt<220)squash=.7;else if(moving&&!reduced)squash=1+Math.sin(now*.018)*.07;const bounce=moving&&!reduced?Math.abs(Math.sin(now*.014))*5*s:0;ctx.save();ctx.beginPath();ctx.ellipse(px,py+unit*.08,unit*.32,unit*.10,0,0,7);ctx.fillStyle='#48698a28';ctx.fill();if(ditto.complete&&ditto.naturalWidth){ctx.drawImage(ditto,px-unit/(squash)*.5,py-unit*squash*.78-bounce,unit/squash,unit*squash)}ctx.restore();
 hint.textContent=near?tr('靠近《'+near.zh+'》，碰一碰就打开。','Touch “'+near.en+'” to open.'):tr('点地面移动，或用 WASD / 方向键。','Click the floor, or use WASD / arrow keys.');requestAnimationFrame(roomLoop);}
renderText();resize();const fallScript=document.createElement('script');fallScript.type='module';fallScript.src='classic-flight.js';document.head.append(fallScript);
