import {TW,TH,BASE,buildTrail,newWalker,nearestItem,advanceWalker,capturePose} from './trail-engine.mjs?v=10';
import {trailRecords} from './trail-data.js?v=10';
import {createStory,turnStory,tickStory,storyDuration} from './story-stack.mjs?v=10';
import {siteConfig,authoredWorld} from './site-config.js?v=10';
import {watchAsset,assetNotice,bindGameButton,fallbackSheet} from './asset-loader.mjs?v=10';
const css=document.createElement('link');css.rel='stylesheet';css.href='trail.css?v=10';document.head.append(css);
const reader=document.querySelector('#reader'),pane=document.querySelector('#reader-content');
const routes=['hi','make','play','watch'],states=new Map(),held=new Set();
let current=null,canvas=null,context=null,popup=null,jump=false,last=0,accumulator=0,nearId=null,disposed=false;
const surface=document.createElement('canvas');surface.width=TW;surface.height=TH;const g=surface.getContext('2d');
// One native pixel-art source for all 151 Kanto species; loaded on demand.
const npcImages=new Map();
const berryNames=['cheri','chesto','pecha','rawst','aspear','leppa','oran','persim','lum','sitrus','nanab','pinap','figy','wiki','mago','aguav','iapapa','razz','bluk','wepear','pomeg','kelpsy','qualot','hondew'];
const berryImages=new Map();
let ballImage=new Image();watchAsset('trail-props','assets/pixel-props.webp',im=>{ballImage=im;});
const fallbackBall=fallbackSheet('props')[0],fallbackDitto=fallbackSheet('ditto');
let ditto=new Image(),meadow=new Image();watchAsset('trail-ditto','assets/pixel-ditto.webp',im=>{ditto=im;});watchAsset('trail-background','assets/pixel-meadow.webp',im=>{meadow=im;});
const data=trailRecords(content,courses);const worldFor=id=>authoredWorld(id,()=>buildTrail(data[id],routes.indexOf(id)));
const palettes={hi:['#dbddf6','#bccbdb','#92b1b4','#668b93'],make:['#d8dff8','#bbcdea','#9eadd1','#6e81aa'],play:['#e2d9f4','#c8bade','#b19bc8','#8975a5'],watch:['#d9e5f5','#b8d5df','#93bcca','#648da7']};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tx=a=>a[lang==='zh'?0:1];
let story=null,removeAssetNotice=null;
let seen;try{seen=new Set(JSON.parse(localStorage.getItem('josie-trail-seen-v1')||'[]'));}catch{seen=new Set();}
function mark(item){seen.add(item.id);try{localStorage.setItem('josie-trail-seen-v1',JSON.stringify([...seen]));}catch{}updateHUD();}
function clear(){held.clear();jump=false;}
const npcNames=[['皮卡丘','Pikachu'],['杰尼龟','Squirtle'],['妙蛙种子','Bulbasaur'],['伊布','Eevee'],['喷火龙','Charizard'],['胖丁','Jigglypuff']];
function closePopup(){if(!popup)return;const catalog=popup.catalog;popup=null;story=null;document.querySelector('.trail-modal')?.remove();document.querySelector('.scene-bubble')?.remove();if(catalog){clear();canvas?.focus({preventScroll:true});}}
function showItem(item){if(!current||popup?.catalog||popup?.id===item.id)return;closePopup();popup=item;mark(item);current.walker.encounterLatch=item.id;
 const cards=item.cards?.length?item.cards:[{title:item.title,body:item.body,image:item.image}];
 story={...createStory(cards.length,matchMedia('(prefers-reduced-motion: reduce)').matches),cards};
 const el=document.createElement('section');el.className='scene-bubble story-bubble';el.setAttribute('role','region');el.setAttribute('aria-label',tx(item.title));
 el.innerHTML=`<div class="bubble-top"><small>${esc(tx(item.title))}</small><button data-dismiss aria-label="${tr('关闭气泡','Close bubble')}">×</button></div><div class="story-deck" aria-live="polite"></div>${item.id==='hello'?'<div class="trail-contact"><a href="mailto:zzxjosie@gmail.com">Email ↗</a><a href="https://www.linkedin.com/in/josiezzx" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="https://github.com/Josie-XX" target="_blank" rel="noopener noreferrer">GitHub ↗</a></div>':''}<div class="story-controls" ${cards.length===1?'hidden':''}><button data-prev>${tr('← 上一张','← Previous')}</button><span data-position role="status"></span><button data-auto></button><button data-next>${tr('下一张 →','Next →')}</button></div>`;
 document.querySelector('.trail-stage').append(el);
 el.querySelector('[data-dismiss]').onclick=closePopup;
 el.querySelector('[data-prev]').onclick=()=>{turnStory(story,-1);renderStory();};
 el.querySelector('[data-next]').onclick=()=>{turnStory(story,1);renderStory();};
 el.querySelector('[data-auto]').onclick=()=>{story.paused=!story.paused;story.elapsed=0;updateStoryControls();if(!story.paused)canvas?.focus({preventScroll:true});};
 renderStory();
}
function updateStoryControls(){if(!story)return;const el=document.querySelector('.story-bubble');if(!el)return;
 el.querySelector('[data-position]').textContent=(story.index+1)+' / '+story.count;
 el.querySelector('[data-prev]').disabled=story.index===0;
 el.querySelector('[data-next]').disabled=story.index===story.count-1;
 const auto=el.querySelector('[data-auto]');auto.disabled=story.index===story.count-1;auto.textContent=story.index===story.count-1?tr('已看完','Finished'):story.paused?tr('自动叠放','Auto-play'):tr('暂停叠放','Pause cards');auto.setAttribute('aria-pressed',String(!story.paused));
}
function renderStory(){const deck=document.querySelector('.story-deck');if(!deck||!story)return;
 deck.innerHTML=story.cards.slice(Math.max(0,story.index-2),story.index+1).map((card,i,visible)=>{const depth=visible.length-1-i;return `<article class="story-card ${depth?'past':'active'}" style="--depth:${depth}" ${depth?'aria-hidden="true" inert':''}><h3>${esc(tx(card.title))}</h3><p>${esc(tx(card.body))}</p>${card.image?`<img src="${esc(card.image)}" alt="${esc(tx(card.title))}">`:''}</article>`;}).join('');
 updateStoryControls();positionBubble();
}
function advanceStory(dt){if(!story||!popup||popup.catalog)return;const el=document.querySelector('.story-bubble');
 const blocked=document.hidden||current.walker.paused||current.walker.gameOver||el?.matches(':hover')||el?.contains(document.activeElement);
 if(tickStory(story,dt,storyDuration(tx(story.cards[story.index].body)),blocked))renderStory();
}
function positionBubble(){const el=document.querySelector('.scene-bubble');if(!el||!current||!canvas||!popup||popup.catalog)return;const r=canvas.getBoundingClientRect(),scale=Math.min(r.width/TW,r.height/TH),offsetX=(r.width-TW*scale)/2,offsetY=(r.height-TH*scale)/2;const anchor=offsetX+(popup.x-current.walker.camera)*scale,width=Math.min(410,r.width-30);el.style.width=width+'px';el.style.left=Math.max(15,Math.min(r.width-width-15,anchor-width/2))+'px';const bottom=offsetY+(popup.y-(popup.kind==='npc'?65:20))*scale;el.style.top=Math.max(105,bottom-el.offsetHeight-18)+'px';el.style.setProperty('--tail',Math.max(20,Math.min(width-20,anchor-parseFloat(el.style.left)))+'px');}
function healthHUD(){if(!current)return;const hp=current.walker.health;const el=document.querySelector('#trail-hearts');if(el){el.setAttribute('aria-label',tr('生命：','Health: ')+(hp/2)+' / 5');el.innerHTML=Array.from({length:5},(_,i)=>`<span class="pixel-heart ${hp>=i*2+2?'full':hp===i*2+1?'half':'empty'}" aria-hidden="true"></span>`).join('');}}
function lifeEvent(event){closePopup();clear();healthHUD();document.querySelector('.trail-life-message')?.remove();const el=document.createElement('div');el.className='trail-life-message';el.setAttribute('role','status');el.innerHTML=event.type==='gameover'?`<h3>${tr('休息一下，再出发','Take a breath. Try again.')}</h3><p>${tr('生命已用完，已发现的记录会保留。','No hearts left. Discovered records are kept.')}</p><button>${tr('重新开始 · 5 颗心','Restart · 5 hearts')}</button>`:`<span>${tr('− ½ ♥ · 回到安全位置','− ½ ♥ · Back to safety')}</span>`;document.querySelector('.trail-stage').append(el);if(event.type==='gameover')el.querySelector('button').onclick=()=>{current.walker=newWalker();el.remove();clear();updateHUD();};else setTimeout(()=>el.remove(),1800);}
function showCatalog(){if(popup?.catalog)return;closePopup();popup={catalog:true};clear();const el=document.createElement('div');el.className='trail-modal';el.innerHTML=`<section class="trail-card" role="dialog" aria-modal="true" aria-labelledby="trail-popup-title"><header><h2 id="trail-popup-title">${tr('内容目录','Contents')}</h2><button data-dismiss aria-label="${tr('关闭','Close')}">✕</button></header><div class="trail-catalog"><button data-replay>${tr('重新探索本页','Explore this page again')}</button>${current.world.items.map((it,i)=>`<button data-record="${i}"><span>${esc(tx(it.title))}</span><small>${seen.has(it.id)?'✓':'✧'}</small></button>`).join('')||`<p>${tr('暂时没有添加记录。可以先在关卡里走走。','No records yet. You can still explore the trail.')}</p>`}</div></section>`;el.querySelector('.trail-catalog').insertAdjacentHTML('beforeend','<p class="trail-credit">Pixel sprites: <a href="https://github.com/PokeAPI/sprites" target="_blank" rel="noopener noreferrer">PokéAPI</a> · Pokémon © Nintendo / Creatures / GAME FREAK</p>');reader.append(el);el.addEventListener('click',e=>{if(e.target===el||e.target.closest('[data-dismiss]'))closePopup();if(e.target.closest('[data-replay]')){current.world.items.forEach(it=>seen.delete(it.id));try{localStorage.setItem('josie-trail-seen-v1',JSON.stringify([...seen]));}catch{}closePopup();current.walker=newWalker();updateHUD();return;}const b=e.target.closest('[data-record]');if(b){const it=current.world.items[Number(b.dataset.record)];closePopup();Object.assign(current.walker,{x:it.x,y:it.y,vy:0,vx:0,grounded:true,camera:Math.max(0,Math.min(current.world.width-TW,it.x-TW*.34))});showItem(it);}});el.querySelector('[data-dismiss]').focus();}
function updateHUD(){if(!current||!canvas)return;const w=current.walker,it=nearestItem(w,current.world),near=document.querySelector('#trail-near');nearId=it?.id??null;
 if(near){near.textContent=it?`${seen.has(it.id)?'✓':'✧'} ${tx(it.title)} · ${it.kind==='image'?tr('靠近树果查看','Approach the berry'):tr('靠近自动查看','Approach to view')}`:tr('← → / A D 移动 · W / ↑ / 空格跳跃 · 靠近自动查看','← → / A D move · W / ↑ / Space jump · Approach to view');}
 canvas.setAttribute('aria-label',tr('内页探索游戏。左右或 AD 移动，上键、W 或空格跳跃，靠近自动查看。五颗心，掉坑扣半颗心。','Content exploration game. Arrows or AD to move; up, W or Space to jump; approach to view. Five hearts; falling costs half a heart.'));
 document.querySelector('#trail-count').textContent=current.world.items.length?`${current.world.items.filter(i=>seen.has(i.id)).length} / ${current.world.items.length} ${tr('已发现','found')}`:tr('记录待添加','Records coming soon');
 healthHUD();const p=document.querySelector('#trail-pause');p.textContent=w.paused?tr('继续 · P','Resume · P'):tr('暂停 · P','Pause · P');p.setAttribute('aria-pressed',String(w.paused));
}
const previousFill=fillReader;
fillReader=id=>{const aliases={about:'hi',life:'hi',games:'play',research:'make',courses:'make'};id=aliases[id]||id;
 if(!routes.includes(id)){closePopup();current=null;reader.classList.remove('trail-reader');previousFill(id);return;}
 const same=current?.id===id&&!!document.querySelector('#trail-canvas');if(same){document.querySelector('#reader-kicker').innerHTML=nav(id);document.querySelector('#trail-name').textContent=nodes.find(n=>n.id===id)[lang];document.querySelector('#trail-order').textContent=tr('向右探索 · 认识我','Explore right · get to know me');document.querySelector('#trail-index').textContent=tr('内容目录','Contents');if(popup){const old=popup;closePopup();old.catalog?showCatalog():showItem(old);}updateHUD();if(current.walker.gameOver)lifeEvent({type:'gameover'});return;}
 closePopup();document.querySelector('.trail-life-message')?.remove();clear();if(!states.has(id))states.set(id,{id,world:worldFor(id),walker:newWalker()});current=states.get(id);reader.dataset.page=id;reader.classList.add('trail-reader');
 document.querySelector('#reader-kicker').innerHTML=nav(id);
 pane.innerHTML=`<div class="trail-stage"><canvas id="trail-canvas" tabindex="0" aria-label="${tr('内页探索游戏。左右或 AD 移动，上键、W 或空格跳跃，靠近自动查看。五颗心，掉坑扣半颗心。','Content exploration game. Arrows or AD to move; up, W or Space to jump; approach to view. Five hearts; falling costs half a heart.')}"></canvas><div class="trail-heading"><h2 id="trail-name">${nodes.find(n=>n.id===id)[lang]}</h2><p id="trail-order">${tr('向右探索 · 认识我','Explore right · get to know me')}</p></div><div class="trail-hud"><div id="trail-hearts" role="img"></div><span id="trail-count"></span><button id="trail-index">${tr('内容目录','Contents')}</button><button id="trail-pause"></button></div><div class="trail-near" id="trail-near" aria-live="polite"></div><div class="trail-touch"><button data-move="left" aria-label="Left">←</button><button data-move="right" aria-label="Right">→</button><button data-move="jump" aria-label="Jump">↑</button></div></div>`;
 canvas=document.querySelector('#trail-canvas');context=canvas.getContext('2d');canvas.addEventListener('pointerdown',()=>canvas.focus({preventScroll:true}));document.querySelector('#trail-index').onclick=showCatalog;document.querySelector('#trail-pause').onclick=()=>{current.walker.paused=!current.walker.paused;clear();updateHUD();};
 document.querySelectorAll('[data-move]').forEach(b=>bindGameButton(b,()=>{const k=b.dataset.move;if(k==='jump')jump=true;else held.add(k);},()=>held.delete(b.dataset.move)));removeAssetNotice?.();removeAssetNotice=assetNotice(document.querySelector('.trail-stage'));updateHUD();if(current.walker.gameOver)lifeEvent({type:'gameover'});
};
function nav(id){return `<button data-home>${tr('← 返回主页','← Home')}</button><nav>${nodes.map(n=>`<button data-open="${n.id}" ${n.id===id?'aria-current="page"':''}>${n[lang]}</button>`).join('')}</nav><button data-language>${lang==='zh'?'Language · EN':'Language · 中文'}</button>`;}
reader.addEventListener('close',()=>{removeAssetNotice?.();removeAssetNotice=null;closePopup();clear();current=null;canvas=null;context=null;reader.classList.remove('trail-reader');});
window.addEventListener('blur',clear);document.addEventListener('visibilitychange',()=>{clear();last=0;accumulator=0;});
window.addEventListener('keydown',e=>{if(!reader.open||!current||e.ctrlKey||e.metaKey||e.altKey)return;const key=e.key.toLowerCase();
 if(popup?.catalog){if(key==='escape'){e.preventDefault();e.stopImmediatePropagation();if(!e.repeat)closePopup();}else if(key==='tab'){const all=[...document.querySelectorAll('.trail-modal button,.trail-modal a')];if(!all.length)return;const first=all[0],end=all.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();end.focus();}else if(!e.shiftKey&&document.activeElement===end){e.preventDefault();first.focus();}}else if(['arrowleft','arrowright','arrowup','a','d','w',' '].includes(key))e.preventDefault();return;}
 if(current.walker.returning){e.preventDefault();return;}
 if(e.target.closest?.('.story-bubble button,.story-bubble a')&&[' ','enter'].includes(key))return;
 if(key==='escape'&&popup){e.preventDefault();e.stopImmediatePropagation();closePopup();return;}
 if(['arrowleft','arrowright','a','d','w','arrowup',' ','p','shift'].includes(key)){e.preventDefault();e.stopImmediatePropagation();if(key==='a'||key==='arrowleft')held.add('left');else if(key==='d'||key==='arrowright')held.add('right');else if(key==='shift')held.add('run');else if(!e.repeat){if(['w','arrowup',' '].includes(key))jump=true;else if(key==='p'){current.walker.paused=!current.walker.paused;clear();updateHUD();}}}
},true);
window.addEventListener('keyup',e=>{const k=e.key.toLowerCase();if(['a','arrowleft'].includes(k))held.delete('left');if(['d','arrowright'].includes(k))held.delete('right');if(k==='shift')held.delete('run');},true);
function rect(x,y,w,h,color){g.fillStyle=color;g.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h));}
function label(s,x,y,size=14,color='#574775',align='center'){g.font=`${size}px "Bradley Hand", "PingFang SC", sans-serif`;g.fillStyle=color;g.textAlign=align;g.fillText(s,x,y);}
function flower(x,y,color='#fff4fb'){rect(x,y-12,2,12,'#839d9b');rect(x-4,y-16,10,5,color);rect(x-2,y-19,6,11,color);rect(x,y-15,2,3,'#d9ca98');}
function grass(x,y){for(let i=0;i<8;i++){rect(x-30+i*8,y-12-(i%3)*8,6,12+(i%3)*8,i%2?'#94b5ad':'#abc8b5');rect(x-34+i*8,y-10,5,7,'#cfddca');}}
function drawNPC(index,x,bottom){if(!npcImages.has(index)){npcImages.set(index,null);watchAsset('npc-'+index,'assets/kanto/'+index+'.png',im=>npcImages.set(index,im));}const im=npcImages.get(index);if(im?.naturalWidth)g.drawImage(im,x-64,bottom-116,128,128);else{g.globalAlpha=.6;g.drawImage(fallbackDitto[0],x-30,bottom-60,60,60);g.globalAlpha=1;label('…',x,bottom-70,20);}}
function berry(index,x,y){const key=index%berryNames.length;if(!berryImages.has(key)){berryImages.set(key,null);watchAsset('berry-'+key,'assets/berries/'+berryNames[key]+'.png',im=>berryImages.set(key,im));}const im=berryImages.get(key);if(im?.naturalWidth)g.drawImage(im,x-32,y-52,64,64);else flower(x,y,'#f6c9de');}
function drawFinish(w,world){const f=world.finish,all=world.items.length>0&&world.items.every(i=>seen.has(i.id));if(all&&Math.abs(w.x-f.flagX)<TW*.6&&current.flagStarted==null)current.flagStarted=w.time;if(!all)current.flagStarted=null;const rise=all&&current.flagStarted!=null?Math.min(1,(w.time-current.flagStarted)/1.2):0,fy=f.y-45-rise*110;rect(f.flagX,f.y-182,5,182,'#827999');rect(f.flagX-4,f.y-187,13,8,'#eeeaff');rect(f.flagX+5,fy,58,30,all?'#b2d7c2':'#e4cfdf');rect(f.flagX+5,fy,58,5,'#fff2f7');label(all?'✓':'✧',f.flagX+31,fy+23,18,'#70647e');label(all?tr('已全部发现！','Everything discovered!'):tr('发现记录，升起旗子','Find every record to raise the flag'),f.flagX,f.y-211,18);const near=Math.abs(w.x-f.portalX)<105;rect(f.portalX-32,f.y,64,6,'#ede1f4');if(ballImage.complete&&ballImage.naturalWidth){const sw=ballImage.naturalWidth/2,sh=ballImage.naturalHeight/2;const open=capturePose(w,world).open*17;g.drawImage(ballImage,sw*.24,sh*.28,sw*.56,sh*.28,f.portalX-28,f.y-60-open,56,28);g.drawImage(ballImage,sw*.24,sh*.56,sw*.56,sh*.28,f.portalX-28,f.y-32+open*.3,56,28);}else g.drawImage(fallbackBall,f.portalX-28,f.y-60,56,56);label(tr('返回首页','Back home'),f.portalX,f.y-80,16);if(near)label(tr('靠近精灵球传送','Approach to return'),f.portalX-30,f.y+37,13);}
function routeBackdrop(w,world,far,mid){g.save();g.globalAlpha=.4;for(let i=-1;i<9;i++){const x=i*190-(w.camera*.17%190),y=250+(i*29%70);if(world.theme===1){rect(x+25,y,45,BASE-y,far);rect(x+95,y-70,38,BASE-y+70,mid);rect(x+10,y-12,72,12,'#f2effb');rect(x+85,y-82,58,12,'#f2effb');for(let k=0;k<4;k++){rect(x+34,y+20+k*40,8,15,'#f7f2ff');rect(x+107,y-40+k*48,8,17,far);}}else if(world.theme===2){rect(x,y,130,17,far);rect(x+18,y-14,98,16,'#f8f0ff');rect(x+43,y-27,48,15,'#f8f0ff');rect(x+25,y+17,84,15,mid);rect(x+45,y+32,43,16,mid);}else{for(let k=0;k<5;k++)rect(x-k*18,y+k*34,85+k*36,BASE-y-k*34, k%2?far:mid);rect(x+5,y-6,65,9,'#f4f4ff');}}g.restore();}
function drawWorld(){if(!current||!canvas||!context)return;const {walker:w,world}=current,[sky,far,mid,dark]=Object.values(palettes)[world.theme];rect(0,0,TW,TH,sky);g.imageSmoothingEnabled=false;
 if(meadow.complete&&meadow.naturalWidth){g.globalAlpha=.35;g.drawImage(meadow,0,0,TW,TH);g.globalAlpha=1;}
 if(world.theme!==0)routeBackdrop(w,world,far,mid);
 if(world.theme===0)for(let layer=0;layer<2;layer++)for(let i=-1;i<12;i++){const x=i*130-(w.camera*(.12+layer*.13)%130),top=155+(i*43+layer*38)%100;g.globalAlpha=layer?.65:.45;rect(x+33,top+35,17,BASE-top,layer?mid:far);rect(x+36,top+65,4,BASE-top-40,far);rect(x+20,top+86,17,5,mid);rect(x+46,top+60,19,5,mid);rect(x,top,86,45,layer?mid:far);rect(x+13,top-24,61,26,layer?mid:far);rect(x+22,top-38,43,16,layer?mid:far);for(let leaf=0;leaf<14;leaf++){const lx=x+6+(leaf*29)%73,ly=top-15+(leaf*17)%55;rect(lx,ly,5+(leaf%3)*3,4,layer?far:sky);if(leaf%4===0)rect(lx+3,ly+4,3,5,sky);}g.globalAlpha=1;}
 rect(0,BASE+12,TW,TH-BASE-12,'#a3a4c9');g.save();g.translate(-Math.round(w.camera),0);
 for(const p of world.terrain){const bottom=p.platform?p.y+16:TH;rect(p.x,p.y,p.w,bottom-p.y,dark);rect(p.x,p.y,p.w,5,'#f3eefa');rect(p.x,p.y+5,p.w,8,mid);for(let x=p.x+8;x<p.x+p.w;x+=21){rect(x,p.y+10,10,4,far);for(let y=p.y+22;y<bottom;y+=24)rect(x+(y%3)*2,y,5+(x%4),5,mid+'65');}}
 for(let x=60;x<world.width;x+=190){const surfaces=world.terrain.filter(p=>x>=p.x&&x<=p.x+p.w);if(!surfaces.length)continue;const y=surfaces.reduce((a,p)=>Math.min(a,p.y),BASE);if(x%4!==0)flower(x,y);else if(current.id!=='watch')grass(x,y);}
 for(const d of world.decorations||[]){if(d.kind==='flower')flower(d.x,d.y);else grass(d.x,d.y);}
 world.items.forEach((it,i)=>{
 const picked=seen.has(it.id),isNear=nearId===it.id;
 if(it.kind==='npc')drawNPC(it.npc,it.x,it.y);else berry(it.berry,it.x,it.y);
 if(!picked){const yy=it.y-(it.kind==='npc'?112:64);const a=.5+Math.sin(w.time*3+i)*.4;g.globalAlpha=a;rect(it.x-2,yy-7,4,14,'#fff8ce');rect(it.x-7,yy-2,14,4,'#fff8ce');g.globalAlpha=1;}
 if(isNear){const title=tx(it.title);label(title.length>25?title.slice(0,24)+'…':title,it.x,it.y-(it.kind==='npc'?132:85),16);}else if(picked)label('✓',it.x,it.y-(it.kind==='npc'?110:60),13,'#75668b');
 });
 drawFinish(w,world);
 // The established Ditto sheet is reused, including its original alpha channel.
 if(ditto.complete&&ditto.naturalWidth){g.globalAlpha=w.hurt>0?(Math.floor(w.time*12)%2?.35:1):1;const frame=!w.grounded?3:Math.abs(w.vx)>0?(Math.floor(w.time*8)%2?1:2):0,sw=ditto.naturalWidth/2,sh=ditto.naturalHeight/2;g.save();const pose=capturePose(w,world);g.globalAlpha*=pose.alpha;g.translate(pose.x,pose.y+8);g.scale(pose.scale,pose.scale);if(w.face<0)g.scale(-1,1);g.drawImage(ditto,(frame%2)*sw,Math.floor(frame/2)*sh,sw,sh,-35,-62,70,70);g.restore();g.globalAlpha=1;} else {const pose=capturePose(w,world);g.save();g.globalAlpha=pose.alpha;g.translate(pose.x,pose.y+8);g.scale(pose.scale,pose.scale);if(w.face<0)g.scale(-1,1);g.drawImage(fallbackDitto[Math.floor(w.time*8)%4],-35,-62,70,70);g.restore();}
 g.restore();if(w.paused){rect(0,0,TW,TH,'#eee9ff99');label(tr('已暂停 · P 继续','Paused · P to resume'),TW/2,TH/2,28);}
 const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),cw=Math.round(r.width*dpr),ch=Math.round(r.height*dpr);if(canvas.width!==cw||canvas.height!==ch){canvas.width=cw;canvas.height=ch;}context.imageSmoothingEnabled=false;context.fillStyle=sky;context.fillRect(0,0,cw,ch);const s=Math.min(cw/TW,ch/TH);context.drawImage(surface,(cw-TW*s)/2,(ch-TH*s)/2,TW*s,TH*s);
}
function frame(t){const dt=last?Math.min((t-last)/1000,.07):0;last=t;if(reader.open&&current&&canvas){accumulator+=dt;while(accumulator>=1/120){const item=advanceWalker(current.walker,current.world,{left:held.has('left'),right:held.has('right'),run:held.has('run'),jump,blocked:!!popup?.catalog||document.hidden},1/120);jump=false;accumulator-=1/120;if(item?.type==='encounter')showItem(item.item);else if(item?.type==='capture'){closePopup();clear();}else if(item?.type==='home'){closePopup();clear();current.walker=newWalker();reader.close();break;}else if(item)lifeEvent(item);}if(!current||!canvas){requestAnimationFrame(frame);return;}const id=nearestItem(current.walker,current.world)?.id??null;if(id!==nearId)updateHUD();if(popup&&!popup.catalog&&(Math.abs(current.walker.x-popup.x)>160||Math.abs(current.walker.y-popup.y)>150))closePopup();advanceStory(dt);drawWorld();positionBubble();}else accumulator=0;requestAnimationFrame(frame);}
requestAnimationFrame(frame);
// Optional local image records. No invented viewing history or placeholder screenshots.
fetch('trail-media.json',{cache:'no-store'}).then(r=>r.json()).then(extra=>{for(const id of ['play','watch']){if(siteConfig?.routes?.[id]||!Array.isArray(extra[id]))continue;for(const [i,record] of extra[id].entries()){if(!/^assets\/[a-zA-Z0-9_./-]+\.(png|jpg|jpeg|webp)$/i.test(record.image||'')||!Array.isArray(record.title)||record.title.length!==2)continue;data[id].push({id:record.id||`${id}-photo-${i}`,title:record.title,body:['',''],image:record.image,kind:'image'});}if(states.has(id))states.get(id).world=buildTrail(data[id],routes.indexOf(id));}}).catch(()=>{});
